# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.UUIDField(verbose_name='islem kodu')),
                ('application_code', models.BigIntegerField(default=510, editable=False)),
                ('alt_module_name', models.CharField(choices=[('Hizmet Listeleme', 0), ('Hizmet Ekleme', 1), ('Hizmet Silme', 2)], max_length=50)),
                ('input_detail', models.TextField(max_length=20000)),
                ('output_detail', models.TextField(max_length=20000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.CharField(max_length=50)),
                ('input2', models.CharField(max_length=50)),
                ('input3', models.CharField(choices=[('Choice 1', 0), ('Choice 2', 1), ('Choice 3', 2)], max_length=50)),
                ('input4', models.FloatField()),
                ('input5', models.IntegerField()),
            ],
        ),
    ]
