# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='alt_module_name',
            field=models.CharField(choices=[(0, 'Hizmet Listeleme'), (1, 'Hizmet Ekleme'), (2, 'Hizmet Silme')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service1',
            name='input3',
            field=models.IntegerField(choices=[(0, 'Choice 1'), (1, 'Choice 2'), (2, 'Choice 3')], max_length=50),
        ),
    ]
