# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('training1', '0002_auto_20171024_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_code',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='islem kodu'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
